### ISSUE TITLE
Hotkeys don't work for me

### ISSUE THREAD

**Issue by tandrewnichols** [dagit/annelid#3]
I found this section in the code

```
impl AppConfig {
    fn new() -> Self {
        let modifiers = ::egui::Modifiers::default();
        AppConfig {
            recent_splits: None,
            recent_layout: None,
            recent_autosplitter: None,
            hot_key_start: Some(HotKey {
                key: egui::Key::Num1,
                modifiers,
            }),
            hot_key_reset: Some(HotKey {
                key: egui::Key::Num3,
                modifiers,
            }),
            hot_key_undo: Some(HotKey {
                key: egui::Key::Num8,
                modifiers,
            }),
            hot_key_skip: Some(HotKey {
                key: egui::Key::Num2,
                modifiers,
            }),
            hot_key_pause: Some(HotKey {
                key: egui::Key::Num5,
                modifiers,
            }),
            use_autosplitter: Some(YesOrNo::Yes),
            frame_rate: Some(DEFAULT_FRAME_RATE),
            polling_rate: Some(DEFAULT_POLLING_RATE),
            reset_on_reset: Some(YesOrNo::No),
            global_hotkeys: Some(YesOrNo::Yes),
        }
    }
}
```

and while I'm not a rust dev, I did try these numbers both by themselves and with virtually every modifier combination I could think of and couldn't get anything to happen. I'm on a mac, where there is no number pad, just the number row above the letters, and I wonder if that could have anything to do with it.

**Comment by dagit** [comment]
When I originally did the input handling I used egui, which treats number keys and numpad as the same. Then I switched to something else because that couldn't do global hotkeys. I think the new think makes a distinction between them. It shouldn't be hard to register both in the input handler. I'll try to do that in the next day or two.

**Comment by tandrewnichols** [comment]
Was this included in the recent release? I still can't get any hotkeys to work. What is the combo I should be using? Looks like "alt" + num in the code, although mac doesn't officially have an "alt" key. I assume it should treat "option" the same though?

**Comment by dagit** [comment]
It shouldn't require any combo in the default hotkeys:

`1` to start/split
`2` to skip a split
`3` to reset
`5` to pause
`8` to undo

It does require elevated permissions because global input handling requires some special accessibility stuff on macOS. On linux it requires some special stuff too but I forgot the specific underlying thing. Most distros add an `input` group and adding your user to that is enough usually. I think on windows anything can listen to input globally.

**Comment by dagit** [comment]
I forgot to mention, on macOS it should ask for the permissions the first time you run it. And then you have to approve them in the control panel thingy.

**Comment by tandrewnichols** [comment]
Hmm, I have accessibility turned on for annelid. It didn't prompt me to do it again when I upgraded though, so I don't know if that matters. But definitely, the numbers aren't doing anything by themselves.

<img width="483" alt="Screenshot 22" src="https://user-images.githubusercontent.com/2755760/229554858-83575d27-7966-499a-9432-5fc11dc049bc.png">
